---
title: "Data Quality Report"
output: html_document
params:
  path: NA 
  human.readable: "Duty of Candor"

---

```{r setup, echo=F}
knitr::opts_chunk$set(echo=F, warning=F, message = F)

style_table <- function(data){
  DT::datatable(
    data,
    options = list(scrollX = TRUE)
  )
}

add.name <- function(data, name){
  data$DataSet <- name
  return(data) 
}

comma.summary <- function(data, name){
  
  c(
    Dataset = name,
    `Comma prop` = sum(data[names(data) != 0 ])/sum(data)
  )
}
```

## Overview

``` {r}
{
  library(tidyverse)
}

data.summary <- function(data) {
  modal <- data$Modal
  missing <- data$Missing
    
  c(`N var` = data$Dimensions[2],
    `N row` = data$Dimensions[1],
    "100% Missing" = sum(missing$Proportion == 1),
    "> 80% Missing" = sum(missing$Proportion != 1),
    "100% Modal" = sum(modal$Proportion == 1),
    "> 80% Modal" = sum(modal$Proportion != 1)
  )
}

data <- readRDS(params$path)

report <- do.call(rbind, lapply(data, f)) 

as_tibble(report, rownames="Dataset") %>% style_table()

```

## Missing Proportions

``` {r}
missing <- do.call(
  rbind, 
  lapply(names(data), function(i) add.name(data[[i]]$Missing, i))
) %>% 
  as_tibble()

tryCatch(
  missing %>% mutate(Proportion = round(as.numeric(Proportion), 3)),
  error = function(e) missing
) %>%
  style_table()

```

## Modal Proportions

``` {r}

modal <- do.call(
  rbind, 
  lapply(names(data), function(i) add.name(data[[i]]$Modal, i))
) %>% 
  as_tibble()

tryCatch(
  modal %>% mutate(Proportion = round(as.numeric(Proportion), 3)),
  error = function(e) modal
) %>%
  style_table()


```

## Comma Presense

``` {r}

do.call(
  rbind, 
  lapply(names(data), function(i) comma.summary(data[[i]]$Comma, i))
) %>% 
  as_tibble() %>% 
  mutate(`Comma prop` = round(as.numeric(`Comma prop`), 3)) %>%
  style_table()


comma <- do.call(
  rbind, 
  lapply(names(data), function(i) comma.summary(data[[i]]$Comma, i))
) %>% 
  as_tibble()

tryCatch(
  comma %>% mutate(`Comma prop` = round(as.numeric(`Comma prop`), 3)),
  error = function(e) comma
) %>%
  style_table()


```


